
export const subcategoryIcons: { [key: string]: any } = {
  "Rice & Grains": require("../assets/images/Done stocks/Rice & Grains.png"),
  "Pasta & Noodles": require("../assets/images/Done stocks/Pasta & Noodles.png"),
  "Cooking Oils": require("../assets/images/Done stocks/Cooking Oils.png"),
  "Drinks & Juices": require("../assets/images/Done stocks/Drinks & Juices.png"),
  "Instant Meals": require("../assets/images/Done stocks/Instant Meals.png"),
  "Milk & Dairy": require("../assets/images/Done stocks/Milk & Dairy.png"),
  "Spices & Seasonings": require("../assets/images/Done stocks/Spices & Seasonings.png"),
  "Bottled Water": require("../assets/images/Done stocks/Bottled Water.png"),
  "Canned Foods": require("../assets/images/Done stocks/Canned Foods.png"),
  "Baking Supplies": require("../assets/images/Done stocks/Baking Supplies.png"),
  
  "Biscuits & Cookies": require("../assets/images/Done stocks/Biscuits & Cookies.png"),
  "Energy Drinks": require("../assets/images/Done stocks/Energy Drinks.png"),
  "Coffee & Tea": require("../assets/images/Done stocks/Coffee & Tea.png"),
  "Cereals": require("../assets/images/Done stocks/Cereals.png"),
  "Ready-to-Eat Meals": require("../assets/images/Done stocks/Ready-to-Eat Meals.png"),
  "Chocolates & Sweets": require("../assets/images/Done stocks/Chocolates & Sweets.png"),
  "Nuts & Seeds": require("../assets/images/Done stocks/Nuts & Seeds.png"),
  "Chips & Crackers": require("../assets/images/Done stocks/Chips & Crackers.png"),
  "Granola & Bars": require("../assets/images/Done stocks/Granola & Bars.png"),
  "Snacks": require("../assets/images/Done stocks/Snacks.png"),

  "Phones": require("../assets/images/Done stocks/Used Phones.png"), // Fallback to Used Phones
  "Tech & Gadgets": require("../assets/images/Done stocks/Tech & Gadgets.png"),
  "Chargers": require("../assets/images/Done stocks/Chargers.png"),
  "Power Banks": require("../assets/images/Done stocks/Power Banks.png"),
  "Earphones & Headsets": require("../assets/images/Done stocks/Earphones & Headsets.png"),
  "USB Drives": require("../assets/images/Done stocks/USB Drives.png"),
  "Phone Cases": require("../assets/images/Done stocks/Phone Cases.png"),
  "Cables & Adapters": require("../assets/images/Done stocks/Cables & Adapters.png"),
  "Screen Protectors": require("../assets/images/Done stocks/Screen Protectors.png"),
  "Laptop Accessories": require("../assets/images/Done stocks/Laptop Accessories.png"),
  "Bluetooth Devices": require("../assets/images/Done stocks/Bluetooth Devices.png"),

  "Bed Sheets": require("../assets/images/Done stocks/Bed Sheets.png"),
  "Pillows": require("../assets/images/Done stocks/Pillows.png"),
  "Blankets": require("../assets/images/Done stocks/Blankets.png"),
  "Protective Covers": require("../assets/images/Done stocks/Protective Covers.png"),
  "Fans": require("../assets/images/Done stocks/Fans.png"),
  "Mattress Covers": require("../assets/images/Done stocks/Mattress Covers.png"),
  "Curtains": require("../assets/images/Done stocks/Curtains.png"),
  "Storage Solutions": require("../assets/images/Done stocks/Storage Solutions.png"),
  "Bed Frames": require("../assets/images/Done stocks/Bed Frames.png"),
  "Laundry Baskets": require("../assets/images/Done stocks/Laundry Baskets.png"),
  "Home Essentials": require("../assets/images/Done stocks/Home Essentials.png"),

  "Pots & Pans": require("../assets/images/Done stocks/Pots & Pans.png"),
  "Cutlery": require("../assets/images/Done stocks/Cutlery.png"),
  "Kettles": require("../assets/images/Done stocks/Kettles.png"),
  "Hotplates": require("../assets/images/Done stocks/Hotplates.png"),
  "Air Fryers": require("../assets/images/Done stocks/Air Fryers.png"),
  "Microwaves": require("../assets/images/Done stocks/Microwaves.png"),
  "Cooking Tools": require("../assets/images/Done stocks/Cooking Tools.png"),
  "Plates & Bowls": require("../assets/images/Done stocks/Plates & Bowls.png"),
  "Blenders": require("../assets/images/Done stocks/Blenders.png"),
  "Food Containers": require("../assets/images/Done stocks/Food Containers.png"),
  "Kitchen Gear": require("../assets/images/Done stocks/Kitchen Gear.png"),

  "Casual Outfits": require("../assets/images/Done stocks/Casual Outfits.png"),
  "Formal Wear": require("../assets/images/Done stocks/Formal Wear.png"),
  "Community Merch": require("../assets/images/Done stocks/Community Merch.png"),
  "Scarves & Wraps": require("../assets/images/Done stocks/Scarves & Wraps.png"),
  "Graphic Tees": require("../assets/images/Done stocks/Graphic Tees.png"),
  "Caps & Hats": require("../assets/images/Done stocks/Caps & Hats.png"),
  "Hoodies & Jackets": require("../assets/images/Done stocks/Hoodies & Jackets.png"),
  "Socks & Underwear": require("../assets/images/Done stocks/Socks & Underwear.png"),
  "Sneakers": require("../assets/images/Done stocks/Sneakers.png"),
  "Accessories": require("../assets/images/Done stocks/Accessories.png"),
  "Local Fashion": require("../assets/images/Done stocks/Local Fashion.png"),

  "Textbooks": require("../assets/images/Done stocks/Textbooks.png"),
  "Lecture Notes": require("../assets/images/Done stocks/Lecture Notes.png"),
  "Lab Equipment": require("../assets/images/Done stocks/Lab Equipment.png"),
  "Pens & Stationery": require("../assets/images/Done stocks/Pens & Stationery.png"),
  "Planners": require("../assets/images/Done stocks/Planners.png"),
  "Calculators": require("../assets/images/Done stocks/Calculators.png"),
  "Notebooks": require("../assets/images/Done stocks/Notebooks.png"),
  "Highlighters": require("../assets/images/Done stocks/Highlighters.png"),
  "Binders": require("../assets/images/Done stocks/Binders.png"),
  "Past Questions": require("../assets/images/Done stocks/Past Questions.png"),
  "Study Supplies": require("../assets/images/Done stocks/Study Supplies.png"),

  "Laundry Detergent": require("../assets/images/Done stocks/Laundry Detergent.png"),
  "Brooms & Dustpans": require("../assets/images/Done stocks/Brooms & Dustpans.png"),
  "Trash Bags": require("../assets/images/Done stocks/Trash Bags.png"),
  "Disinfectants": require("../assets/images/Done stocks/Disinfectants.png"),
  "Laundry Tools": require("../assets/images/Done stocks/Laundry Tools.png"),
  "Mops & Cleaners": require("../assets/images/Done stocks/Mops & Cleaners.png"),
  "Buckets": require("../assets/images/Done stocks/Buckets.png"),
  "Cleaning Brushes": require("../assets/images/Done stocks/Cleaning Brushes.png"),
  "Air Fresheners": require("../assets/images/Done stocks/Air Fresheners.png"),
  "Pest Control": require("../assets/images/Done stocks/Pest Control.png"),
  "Cleaning & Home": require("../assets/images/Done stocks/Cleaning & Home.png"),

  "Soaps & Shampoos": require("../assets/images/Done stocks/Soaps & Shampoos.png"),
  "First Aid Kits": require("../assets/images/Done stocks/First Aid Kits.png"),
  "Sanitary Pads": require("../assets/images/Done stocks/Sanitary Pads.png"),
  "Painkillers & Meds": require("../assets/images/Done stocks/Painkillers & Meds.png"),
  "Mosquito Repellent": require("../assets/images/Done stocks/Mosquito Repellent.png"),
  "Skincare Products": require("../assets/images/Done stocks/Body Lotions.png"), // Fallback
  "Hair Products": require("../assets/images/Done stocks/Hair Products.png"),
  "Body Lotions": require("../assets/images/Done stocks/Body Lotions.png"),
  "Toothpaste": require("../assets/images/Done stocks/Toothpaste.png"),
  "Deodorants": require("../assets/images/Done stocks/Deodorants.png"),
  "Personal Care": require("../assets/images/Done stocks/Personal Care.png"),

  "Laundry Services": require("../assets/images/Done stocks/Laundry Tools.png"), // Fallback
  "Local Services": require("../assets/images/Done stocks/Local Services.png"),
  "Typing & Printing": require("../assets/images/Done stocks/Typing & Printing.png"),
  "Bike Repairs": require("../assets/images/Done stocks/Bike Repairs.png"),
  "Phone Repairs": require("../assets/images/Done stocks/Phone Repairs.png"),
  "Tutoring Sessions": require("../assets/images/Done stocks/Tutoring Sessions.png"),
  "Room Rentals": require("../assets/images/Done stocks/Room Rentals.png"),
  "Food Delivery": require("../assets/images/Done stocks/Food Stalls.png"), // Fallback
  "Maintenance": require("../assets/images/Done stocks/Maintenance.png"),
  "Haircuts": require("../assets/images/Done stocks/Haircuts.png"),
  "Event Planning": require("../assets/images/Done stocks/Event Planning.png"),

  "Used Phones": require("../assets/images/Done stocks/Used Phones.png"),
  "Used Laptops": require("../assets/images/Done stocks/Used Laptops.png"),
  "Used Furniture": require("../assets/images/Done stocks/Used Furniture.png"),
  "Used Books": require("../assets/images/Done stocks/Used Books.png"),
  "Used Clothes": require("../assets/images/Done stocks/Used Clothes.png"),
  "Used Appliances": require("../assets/images/Done stocks/Used Appliances.png"),
  "Used Electronics": require("../assets/images/Done stocks/Used Electronics.png"),
  "Used Accessories": require("../assets/images/Done stocks/Used Accessories.png"),
  "Used Bikes": require("../assets/images/Done stocks/Used Bikes.png"),
  "Used Gadgets": require("../assets/images/Done stocks/Used Gadgets.png"),
  "Secondhand Deals": require("../assets/images/Done stocks/Secondhand Deals.png"),

  "Pop-up Sales": require("../assets/images/Done stocks/Pop-up Sales.png"),
  "Club Events": require("../assets/images/Done stocks/Club Events.png"),
  "Food Stalls": require("../assets/images/Done stocks/Food Stalls.png"),
  "Hot Deals": require("../assets/images/Done stocks/Hot Deals.png"),
  "Workshops": require("../assets/images/Done stocks/Workshops.png"),
  "Job Fairs": require("../assets/images/Done stocks/Job Fairs.png"),
  "Competitions": require("../assets/images/Done stocks/Competitions.png"),
  "Charity Drives": require("../assets/images/Done stocks/Charity Drives.png"),
  "Parties": require("../assets/images/Done stocks/Parties.png"),
  "Room Listings": require("../assets/images/Done stocks/Room Listings.png"),
  "Community Events": require("../assets/images/Done stocks/Community Events.png"),
};
